# Generated by Django 4.0.4 on 2022-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('code', models.CharField(default=None, max_length=255, unique=True)),
                ('development_mode', models.BooleanField(default=False)),
                ('support_email', models.EmailField(default=None, max_length=254)),
                ('no_reply_email', models.EmailField(default=None, max_length=254)),
                ('developer_email', models.EmailField(default=None, max_length=254)),
                ('timezone', models.CharField(default='UTC', max_length=32)),
            ],
            options={
                'db_table': 'website',
            },
        ),
    ]
