# Generated by Django 4.0.4 on 2022-06-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='developer_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='no_reply_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='support_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
